version: "3"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./code:/app/code
      - ./data:/app/data
      - .vscode/:/app/.vscode
      - ./docker/:/app/docker/
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
