version: "3"

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./code:/app/code
      - ./data:/app/data
    environment:
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no