version: "3"

services:
  app:
    build:
      dockerfile: ./docker/Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./code:/app/code
      - ./data:/app/data
    environment:
      - GIT_SSH_COMMAND=ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]